repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.16.3  # Latest stable version as of January 2025
    wait: true
    timeout: 600
    atomic: true
    values:
      - crds:
          enabled: true
          keep: true

        # Enable Prometheus metrics
        prometheus:
          enabled: true

        # Resource requests/limits
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi

        webhook:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi

        cainjector:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi

  - name: cert-manager-config
    namespace: cert-manager
    chart: ./charts/cert-manager-config
    needs:
      - cert-manager/cert-manager
    wait: true
    values:
      - email: "info@t3company.de"
        server: "prod"
        enableDns01: false
        enableHttp01: true
